GET http://localhost:3002/drivers/

###
POST  http://localhost:3002/drivers/
Content-Type: application/json

{
    "country": "America",
    "point": 2,
    "fullname": "John Cena",
    "champion": 3,
    "number": 15,
    "avt": "https://nationaltoday.com/wp-content/uploads/2022/10/456841065-min-1200x834.jpg"
}


###
PUT  http://localhost:3002/drivers?id=24
Content-Type: application/json

{
    "country": "Viet Nam",
    "point": 2,
    "fullname": "Vrillar VN",
    "champion": 3,
    "number": 15,
    "avt": "https://nationaltoday.com/wp-content/uploads/2022/10/456841065-min-1200x834.jpg"
}